{
 "title": "devops-app",
 "time": { "from": "2023-03-09T21:05:29.338Z", "to": "2023-03-09T21:10:31.524Z" },
 "panels": [
  {
   "title": "HTTP Server requests timing sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(outcome) (http_server_requests_seconds_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Server response times percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) (http_server_requests_seconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Server requests count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Server max response time in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_max[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Client requests timing sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "sum(feign_Client_seconds_sum)", "legendFormat": "__auto" }
   ]
  }
 ]
}